name       : spirv-llvm-translator
version    : 11.0.0
release    : 2
source     :
    - https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/refs/tags/v11.0.0.tar.gz : 6464a722278d37fca783cb505caf44cc8473c22fd22ff6a5d07198bc92059c4f
license    : Apache-2.0-WITH-LLVM-Exception
component  : programming.tools
homepage   : https://github.com/KhronosGroup/SPIRV-LLVM-Translator/
summary    : Tool/library for translation between SPIR-V and LLVM IR
description: |
    A tool and a library for bi-directional translation between SPIR-V and LLVM IR.
clang      : yes
builddeps  :
    - pkgconfig(SPIRV-Tools)
setup      : |
    %patch -p1 < $pkgfiles/0001-set-llvm-version-to-11.1.0.patch
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
