name       : spirv-llvm-translator
version    : 10.0.0
release    : 1
source     :
    - https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/v10.0.0.tar.gz : 7ccde52bac4c9ad967a362a3c5ec7261aa5b7b34d28cef0f3dec38d77c923049
license    : Apache-2.0-WITH-LLVM-Exception
component  : programming.tools
homepage   : https://github.com/KhronosGroup/SPIRV-LLVM-Translator/
summary    : Tool/library for translation between SPIR-V and LLVM IR
description: |
    A tool and a library for bi-directional translation between SPIR-V and LLVM IR.
clang      : yes
builddeps  :
    - pkgconfig(SPIRV-Tools)
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
