name       : spirv-llvm-translator
version    : 12.0.0
release    : 3
source     :
    - https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/refs/tags/v12.0.0.tar.gz : 6e4fad04203f25fcde4c308c53e9f59bd05a390978992db3212d4b63aff62108
license    : Apache-2.0-WITH-LLVM-Exception
component  : programming.tools
homepage   : https://github.com/KhronosGroup/SPIRV-LLVM-Translator/
summary    : Tool/library for translation between SPIR-V and LLVM IR
description: |
    A tool and a library for bi-directional translation between SPIR-V and LLVM IR.
clang      : yes
builddeps  :
    - pkgconfig(SPIRV-Tools)
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
